### PR TITLE
948 upload ingredients from zip

### PR DESCRIPTION
**Pull request by slawosz**
Proper template when adding ingredients files for components from zip file.

### CODE REVIEW

**Comment by nasirkhanbeis** [comment]
looks good to me, detects type of formulation and prompts user on right page. However upload image seems to loop forever for post brexit zip file upload. Please try with attached test file.
[Uploading Multi-Item-RangeDoc_pHRange_ExactDoc_Nano 3.zip…]()

**Comment by nasirkhanbeis** [comment]
Re-tested above issue, seems to be images not being attached at item level but rather at product which looks like different issue. so happy to approve this.

**Review by nasirkhanbeis — APPROVED** [review]
works fine as expected. detects formulation type and puts user to the right page.

**Review by scruti — APPROVED** [review]
LGTM!

**Pull request merged**
