### PR TITLE
CloudFoundry ruby & buildpack update

### PR DESCRIPTION
**Pull request by slorek**
~Do not merge until Buildpack issue gets resolved:
https://github.com/UKGovernmentBEIS/beis-opss/pull/1644#issuecomment-579340652~ (Has been resolved)

## Description
This updates `ruby` to version 2.6.6 and `bundler`, `node` and `yarn` to the new versions supported by the [CloudFoundry Ruby buildpack v1.8.18](https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.18).

## Checklist:

- [ ] Automated checks are passing locally.
- [ ] CHANGELOG updated if change is worth telling users about.
### General testing
- [ ] Test without javascript
- [ ] Test on small screen
### Accessibility testing
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable css - does content make sense and appear in a logical order?
- [ ] Passes automated checker (automated in build or manual)

### CODE REVIEW

**Comment by slorek** [comment]
There is currently an issue with this buildpack using bundler 2.1.4. Do not merge until resolved. See also https://github.com/cloudfoundry/ruby-buildpack/issues/120

**Comment by matthewford** [comment]
> There is currently an issue with this buildpack using bundler 2.1.4. Do not merge until resolved. See also [cloudfoundry/ruby-buildpack#120](https://github.com/cloudfoundry/ruby-buildpack/issues/120)

Was this raised to GDS @slorek ? Just wondering if they gave you a timeline or are we stuck with rolling back bundler.

**Comment by slorek** [comment]
> > There is currently an issue with this buildpack using bundler 2.1.4. Do not merge until resolved. See also [cloudfoundry/ruby-buildpack#120](https://github.com/cloudfoundry/ruby-buildpack/issues/120)
> 
> Was this raised to GDS @slorek ? Just wondering if they gave you a timeline or are we stuck with rolling back bundler.

Yes I raised it on the cross-gov Slack. Their suggestion was to pin the buildpack version which I have done. To be fair I think this is a CloudFoundry issue.

**Comment by scruti** [comment]
@dependabot-bot rebase

**Pull request merged**
